import { PageHeader } from '@/components/ui/PageHeader';
import { GlassCard } from '@/components/ui/GlassCard';
import { ShieldAlert } from 'lucide-react';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background-dark font-body selection:bg-primary/30 antialiased pt-24 pb-20">
            <div className="container mx-auto px-6 max-w-4xl">
                <PageHeader
                    title="Terms of Service"
                    subtitle="Last updated: January 2026"
                    icon={<ShieldAlert className="w-8 h-8 text-red-400" />}
                />

                <GlassCard className="prose prose-invert max-w-none text-slate-300">
                    <h3>1. Acceptance of Terms</h3>
                    <p>
                        By accessing and using KilatOS ("the Service"), you agree to be bound by these Terms of Service.
                    </p>

                    <h3>2. Use of AI Services</h3>
                    <p>
                        KilatOS provides AI-powered code generation and assistance. You acknowledge that AI output may contain errors or inaccuracies.
                        You are responsible for reviewing and vetting all code generated by the Service before using it in production.
                    </p>

                    <h3>3. Intellectual Property</h3>
                    <ul className="list-disc pl-5 space-y-2">
                        <li><strong>Your Input:</strong> You retain all rights to the code and data you input into KilatOS.</li>
                        <li><strong>AI Output:</strong> KilatOS assigns to you all right, title, and interest in the output generated by the Service based on your inputs.</li>
                    </ul>

                    <h3>4. User Conduct</h3>
                    <p>
                        You agree not to use the Service to:
                    </p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li>Generate malicious code or malware.</li>
                        <li>Violate the intellectual property rights of others.</li>
                        <li>Attempt to reverse engineer the Service.</li>
                    </ul>

                    <h3>5. Limitation of Liability</h3>
                    <p>
                        KilatOS is provided "AS IS". We are not liable for any damages arising from the use or inability to use the Service,
                        including but not limited to data loss or business interruption.
                    </p>

                    <div className="pt-8 border-t border-white/10 mt-8">
                        <p className="text-sm text-slate-500">
                            For questions about these terms, please contact <a href="/contact" className="text-primary">legal@kilatos.ai</a>.
                        </p>
                    </div>
                </GlassCard>
            </div>
        </div>
    );
}
