import { PageHeader } from '@/components/ui/PageHeader';
import { GlassCard } from '@/components/ui/GlassCard';
import { HelpCircle } from 'lucide-react';

export default function FAQPage() {
    const faqs = [
        {
            q: "What is KilatOS?",
            a: "KilatOS is a multi-agent AI development platform. It coordinates specialized AI agents (like KilatCode for coding, KilatResearch for data) to handle complex workflows that single LLMs struggle with."
        },
        {
            q: "Is it free to use?",
            a: "Yes! We offer a generous Free Tier that gives you access to basic agents. You can upgrade to Pro for higher daily limits, faster processing, and advanced models."
        },
        {
            q: "How do the Daily Limits work?",
            a: "Each plan has a daily computation budget. Different actions use different amounts (e.g., simple chat vs. complex code generation). Your limit resets automatically daily at midnight UTC."
        },
        {
            q: "Can I use KilatOS for commercial projects?",
            a: "Absolutely. All code and content generated by KilatOS on Pro and Enterprise plans is 100% yours to own and commercialize. Free tier usage is subject to standard open attribution licenses."
        },
        {
            q: "What happens if I reach my limit?",
            a: "If you hit your daily limit, you can either wait for the daily reset or upgrade your plan to instantly increase your cap. Enterprise users have custom limits."
        },
        {
            q: "Is my data secure?",
            a: "Values privacy above all. We do not train our models on Pro/Enterprise data. All active sessions are encrypted, and we offer optional zero-retention modes for sensitive enterprise workflows."
        }
    ];

    return (
        <div className="min-h-screen bg-background-dark font-body selection:bg-primary/30 antialiased pt-24 pb-20">
            <div className="container mx-auto px-6 max-w-3xl">
                <PageHeader
                    title="Frequently Asked Questions"
                    subtitle="Everything you need to know about KilatOS, pricing, and capabilities."
                    icon={<HelpCircle className="w-8 h-8 text-accent-cyan" />}
                />

                <div className="space-y-4">
                    {faqs.map((faq, idx) => (
                        <GlassCard key={idx} className="group hover:border-white/20 transition-all cursor-default">
                            <h3 className="text-lg font-bold text-white mb-2 group-hover:text-primary transition-colors">
                                {faq.q}
                            </h3>
                            <p className="text-slate-400 leading-relaxed">
                                {faq.a}
                            </p>
                        </GlassCard>
                    ))}
                </div>

                <div className="mt-12 text-center">
                    <p className="text-slate-400">
                        Still have questions? <a href="/contact" className="text-primary hover:underline">Contact Support</a>
                    </p>
                </div>
            </div>
        </div>
    );
}
